version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db-final-project
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB:  ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}